### ISSUE TITLE
"ghost" cluster markers in rviz2 

### ISSUE THREAD

**Issue by szepilot** [jkk-research/lidar_cluster_ros2#15]
https://github.com/jkk-research/lidar_cluster_ros2/commit/ebf902936287c2ef07034dd5e1f692393b852a00
https://github.com/jkk-research/lidar_cluster_ros2/commit/27b0e8a079250495fdc3c39d2892a8d78c37f3dc

**Comment by umiklos** [comment]
there are no more "ghost" middle points, but "ghost" polygons are still exist
